Repository algorand/indexer, pull requests merged in 2021-06, with the labels that each got.

#518 Prometheus Metrics Endpoint
  README.md
  api/middlewares/prometheus_path_mapper.go
  api/server.go
  cmd/algorand-indexer/daemon.go
  cmd/block-generator/docker/Dockerfile-generator
  cmd/block-generator/docker/Dockerfile-indexer
  cmd/block-generator/docker/README.md
  cmd/block-generator/docker/docker-compose.yml
  cmd/block-generator/docker/grafana.ini
  cmd/block-generator/docker/grafana_indexer_dashboard.json
  cmd/block-generator/docker/grafana_prometheus_datasource.yml
  cmd/block-generator/docker/prometheus.yml
  go.mod
  go.sum
Labels: Team Carbon-11

#524 Add codecov integration.
  .travis.yml
  Makefile
  scripts/3rd_party/codecov
  scripts/upload_coverage.sh
Labels: Team Carbon-11, Unplanned

#545 Add ExtraProgramPages app call field support
  accounting/accounting.go
  api/converter_utils.go
  api/generate.sh
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/pointer_utils.go
  cmd/validator/struct_processor.go
  go.mod
  go.sum
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  test/common.sh
Labels: Team Scytale, Unplanned

#544 Import performance test runner
  cmd/block-generator/daemon.go
  cmd/block-generator/generator/generate.go
  cmd/block-generator/generator/generate_test.go
  cmd/block-generator/generator/server.go
  cmd/block-generator/runner.go
  cmd/block-generator/runner/metrics_collector.go
  cmd/block-generator/runner/run.go
Labels: Team Carbon-11
