Repository algorand/indexer, pull requests merged in 2021-12, with the labels that each got.

#803 Format schema sql
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
Labels: Unplanned, tech debt, Team Carbon-11

#802 Prepare and write txn rows in parallel
  idb/postgres/internal/writer/util.go
  idb/postgres/internal/writer/writer.go
Labels: Team Carbon-11

#801 Add `IndexerDb.Close()`
  api/handlers_e2e_test.go
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/import.go
  cmd/import-validator/main.go
  fetcher/fetcher.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/testing/testing.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
Labels: Unplanned, Team Carbon-11

#805 Write into `txn` and `txn_participation` tables in parallel with other import procedures
  idb/postgres/internal/writer/write_txn.go
  idb/postgres/internal/writer/write_txn_participation.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Team Carbon-11

#807 Write transactions earlier if possible
  idb/postgres/postgres.go
Labels: Team Carbon-11

#810 Updating readme for postgres 13 and AZ note
  README.md
Labels: Team Hyper Flow

#811 Add a readme for import validator
  cmd/import-validator/README.md
  cmd/import-validator/main.go
Labels: Team Carbon-11
