Repository algorand/indexer, pull requests merged in 2021-10, with the labels that each got.

#694 Better error when validator fails to parse data.
  cmd/validator/core/dynamic_processor.go
  cmd/validator/core/struct_processor.go
Labels: Unplanned, Team Carbon-11

#696 Return extra program pages in app params
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Unplanned, Team Scytale

#689 Clear out error in catchup loop
  fetcher/fetcher.go
Labels: bug, Team Carbon-11

#691 Call `Commit()` in `TxWithRetry()`.
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_rand_test.go
Labels: tech debt, Team Carbon-11

#697 Make `EncodeJSON()` private
  go.mod
  go.sum
  idb/postgres/internal/encoding/decode.go
  idb/postgres/internal/encoding/encode.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/types/types.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: Unplanned, tech debt, Team Carbon-11

#698 backport AVM 1.0 consensus support
  types/protocols.json
  types/protocols_json.go
  types/types.go
Labels: Team Carbon-11

#668 Fetch block concurrently with import
  fetcher/fetcher.go
Labels: Team Carbon-11

#714 Cleanup
  idb/idb.go
  idb/postgres/internal/encoding/encode.go
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
Labels: Team Carbon-11

#667 Use COPY to insert into `txn` and `txn_participation` tables
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: Team Carbon-11

#711 Add a migration that fails telling the user that upgrade is not supported
  idb/postgres/postgres_migrations.go
Labels: Team Carbon-11

#729 Always give nil maps to evaluator when empty
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
Labels: Team Carbon-11

#727 fixes
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Team Carbon-11

#761 Fix inner txn intra
  idb/idb_test.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres_integration_test.go
  util/test/account_testutil.go
Labels: bug, Unplanned, Team Carbon-11
