Repository algorand/indexer, pull requests merged in 2021-08, with the labels that each got.

#600 Fix OpenAPI tooling.
  api/Makefile
  api/README.md
Labels: Team Carbon-11, Unplanned

#605 FOR REVIEW ONLY - indexer 2.6.1
  .version
  Makefile
  mule/sign.sh
  types/protocols.json
  types/protocols_json.go
  types/types.go
Labels: Team Hyper Flow

#585 Delete reverse app deltas
  idb/idb.go
  idb/postgres/postgres.go
Labels: Unplanned, Team Carbon-11

#615 Add missing docker dependencies for go-algorand.
  docker/Dockerfile
  docker/Dockerfile.mule
Labels: Team Carbon-11

#617 Rename helpers in `account_testutil.go`
  accounting/accounting_test.go
  idb/postgres/postgres_integration_test.go
  util/test/account_testutil.go
Labels: Team Carbon-11

#623 Generator Fixes
  cmd/block-generator/generator/generate.go
  cmd/block-generator/generator/make_transactions.go
  cmd/block-generator/runner.go
  cmd/block-generator/runner/run.go
Labels: Unplanned, Team Carbon-11

#625 Move database schema out of postgres
  Makefile
  cmd/texttosource/main.go
  idb/postgres/internal/schema/schema.go
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
  idb/postgres/postgres.go
Labels: Team Carbon-11
