Repository algorand/indexer, pull requests merged in 2021-04, with the labels that each got.

#422 Fix asset holding frozen migration.
  idb/postgres/postgres_migrations.go
Labels: FDE

#455 Reset command
  Makefile
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/import.go
  cmd/algorand-indexer/main.go
  cmd/algorand-indexer/reset.go
  idb/dummy.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_migrations.go
  idb/postgres/reset.sql
  idb/postgres/reset_sql.go
  test/common.sh
Labels: Infrastructure

#464 Fix conflict between initial import refactoring and reset command.
  cmd/algorand-indexer/reset.go
Labels: 0.5, FDE

#460 m7: delete assets (locally) created by accounts that we have already been updated
  idb/postgres/postgres_migrations.go
Labels: FDE, Unplanned
