Repository algorand/indexer, pull requests merged in 2021-11, with the labels that each got.

#765 Use our own json handle for decoding
  idb/postgres/internal/encoding/encode.go
  idb/postgres/internal/encoding/encoding.go
Labels: Team Carbon-11

#760 Improve DB indexes for better worst case accounting time
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
Labels: Team Carbon-11

#763 Use integer for root intra in `TxnExtra`
  api/converter_utils.go
  idb/idb.go
  idb/idb_test.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/writer/writer.go
Labels: Team Carbon-11

#764 Search for serialization error in function's return error
  idb/postgres/internal/util/util.go
  idb/postgres/internal/util/util_test.go
  idb/postgres/postgres.go
Labels: Team Carbon-11

#770 Write app call addresses in `txn_participation` table
  accounting/accounting.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
Labels: Team Carbon-11

#780 Add error msg in rewind about inner txns
  accounting/rewind.go
Labels: Team Carbon-11

#771 Support search by zero address.
  accounting/accounting.go
  api/converter_utils.go
  api/error_messages.go
  api/handlers.go
  api/handlers_test.go
  api/pointer_utils.go
  idb/postgres/internal/writer/writer.go
Labels: Unplanned, Team Carbon-11

#777 Make inner transaction creatable ID lookup more resilient.
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
Labels: Unplanned, Team Carbon-11

#781 Add a test for the `txn.asset` column
  idb/idb.go
  idb/postgres/postgres_integration_test.go
  util/test/account_testutil.go
Labels: Unplanned, Team Carbon-11

#784 Return `TotalAppSchema` and `TotalExtraAppPages` from `AccountData`
  idb/postgres/postgres.go
Labels: Unplanned, Team Carbon-11

#785 Display b64 fields if their content is zero bytes
  api/converter_utils.go
  api/handlers.go
  api/pointer_utils.go
  idb/postgres/postgres.go
Labels: Unplanned, Team Carbon-11

#789 Remove non UTF-8 characters from Inner transaction Asset fields
  idb/postgres/internal/encoding/encode.go
  idb/postgres/postgres_integration_test.go
Labels: Unplanned, Team Scytale

#786 Move timeout handling into handlers.
  api/error_messages.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/server.go
  api/util.go
  api/util_test.go
Labels: Unplanned, Team Carbon-11

#796 Add a check in `idb.DecodeTxnRowNext()` to prevent indexer crash
  idb/idb.go
Labels: Unplanned, Team Carbon-11

#798 Add libboost-math-dev to mule's Dockerfile
  docker/Dockerfile.mule
Labels: Low Priority, Team Hyper Flow

#792 Increase balance of genesis accounts to 1 billion algos
  cmd/block-generator/scenarios/config.payment.full.yml
  cmd/block-generator/scenarios/config.payment.jumbo.yml
  cmd/block-generator/scenarios/config.payment.small.yml
Labels: Team Carbon-11

#749 Preload asset/app creators before evaluation
  idb/postgres/postgres.go
Labels: Team Carbon-11

#772 Delete `txnbytes` column
  accounting/rewind.go
  accounting/rewind_test.go
  api/converter_utils.go
  api/handlers_test.go
  cmd/e2equeries/main.go
  idb/idb.go
  idb/idb_test.go
  idb/postgres/internal/schema/setup_postgres.sql
  idb/postgres/internal/schema/setup_postgres_sql.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  misc/generate_test_files.sh
  util/test/testutil.go
Labels: Team Carbon-11

#783 Update sigtype along with the rest of account data
  idb/postgres/internal/writer/writer.go
  idb/postgres/postgres_integration_test.go
Labels: Team Carbon-11
