Repository algorand/indexer, pull requests merged in 2021-07, with the labels that each got.

#557 Add devmode support to indexer
  types/types.go
Labels: Team Carbon-11

#554 Avoid leaking db transactions and rows
  idb/postgres/postgres.go
Labels: Team Carbon-11, Unplanned

#558 Delete old migrations
  Makefile
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  test/README.md
  test/migrations/create_delete.2.2.1.txt
  test/migrations/cumulative_rewards_dump.txt
  test/postgres_migration_test.sh
Labels: Team Carbon-11, Unplanned

#560 Fix two small bugs in Health()
  idb/postgres/postgres.go
Labels: Team Carbon-11, Unplanned, bug

#559 Store next round in import state
  cmd/algorand-indexer/daemon.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_migrations_integration_test.go
  importer/helper.go
Labels: Team Carbon-11, Unplanned, tech debt

#569 Validator improvements.
  cmd/validator/struct_processor.go
  cmd/validator/validate_accounting.go
Labels: 0.5, Team Carbon-11, Unplanned

#561 Improvements in `idb/postgres/` and `reset.go`
  cmd/algorand-indexer/reset.go
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_test.go
Labels: Team Carbon-11, Unplanned, tech debt

#580 Run e2e test with nightly channel.
  .travis.yml
  misc/Dockerfile
  misc/docker-compose.yml
Labels: Team Carbon-11

#577 non utf8 support for asset strings
  .travis.yml
  Makefile
  api/converter_utils.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/test_resources/asset_config.response
  idb/idb.go
  idb/postgres/internal/encoding/decode.go
  idb/postgres/internal/encoding/encode.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/encoding/types.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  misc/Dockerfile
  misc/docker-compose.yml
  test/common.sh
  types/types.go
  util/util.go
Labels: Team Carbon-11

#591 Add missing validation for b64 fields.
  cmd/validator/struct_processor.go
Labels: Team Carbon-11

#586 daemon: replace a sleep loop with a channel.
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/import.go
  cmd/algorand-indexer/main.go
  cmd/e2equeries/main.go
  cmd/idbtest/idbtest.go
  idb/dummy/dummy_factory.go
  idb/idb_factory.go
  idb/migration/migration.go
  idb/migration/migration_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_factory.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_migrations_integration_test.go
  idb/postgres/postgres_test.go
Labels: Team Carbon-11, bug, tech debt

#595 Allow overriding OS_TYPE and ARCH. This will allow signing locally on e.g. mac
  Makefile
  mule/sign.sh
Labels: Team Hyper Flow

#593 Add support for running integration tests with an external DB.
  idb/postgres/postgres_integration_common_test.go
Labels: Team Carbon-11, Unplanned

#587 Add more prometheus metrics.
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/main.go
  cmd/block-generator/runner/metrics_collector.go
  cmd/block-generator/runner/run.go
  importer/helper.go
  util/metrics/metrics.go
Labels: Team Carbon-11

#599 FOR REVIEW ONLY - indexer 2.6.0 re-merge
  .version
Labels: Team Hyper Flow
