Repository algorand/indexer, pull requests merged in 2021-03, with the labels that each got.

#364 Minor validator tool improvements
  cmd/validator/README.md
  cmd/validator/validate_accounting.go
Labels: FDE, Unplanned, tech debt

#383 Update consensus protocol by adding v26
  types/protocols.json
  types/protocols_json.go
Labels: Infrastructure

#400 Fix tag parsing and mockery install in mule docker
  docker/Dockerfile.mule
  misc/release.py
Labels: Dev Ops
