Repository algorand/indexer, pull requests merged in 2021-09, with the labels that each got.

#629 Replace postgres driver pg with pgx
  cmd/block-generator/runner/run.go
  go.mod
  go.sum
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: performance, Team Carbon-11

#634 Close `ledgerForEval`
  idb/postgres/postgres.go
Labels: Team Carbon-11

#626 Move `ledger_for_evaluator` and `writer` tests to their packages
  go.mod
  go.sum
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/internal/schema/generate.go
  idb/postgres/internal/schema/metastate.go
  idb/postgres/internal/testing/testing.go
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: tech debt, Team Carbon-11

#638 Make `--test-pg` flag correct when running multiple tests
  idb/postgres/internal/testing/testing.go
  idb/postgres/postgres_integration_test.go
Labels: Unplanned, Team Carbon-11

#637 Use "pgx" when opening a database
  idb/postgres/internal/testing/testing.go
Labels: Unplanned, Team Carbon-11

#636 Use context properly with the new postgres driver
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: Unplanned, Team Carbon-11

#639 Add eval time metric to prometheus
  cmd/block-generator/run_runner.sh
  cmd/block-generator/runner/run.go
  idb/postgres/postgres.go
  util/metrics/metrics.go
Labels: Unplanned, Team Carbon-11

#642 Delete `postgres_test.go`
  idb/postgres/postgres_test.go
Labels: Unplanned, Team Carbon-11

#643 Use the native interface of the pgx postgres driver
  cmd/block-generator/runner/run.go
  go.mod
  go.sum
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/internal/testing/testing.go
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: Team Carbon-11

#645 Mock code cleanup
  go.mod
  go.sum
  idb/postgres/mock_driver.go
Labels: tech debt, Team Carbon-11

#649 Add a test for ledger_for_evaluator
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
Labels: Team Carbon-11

#650 Don't ignore an error
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
Labels: bug, Team Carbon-11

#654 Resolve staticcheck lint warnings
  accounting/rewind.go
  api/handlers.go
  api/pointer_utils.go
  cmd/block-generator/generator/generate.go
  cmd/block-generator/generator/server_test.go
  cmd/e2equeries/main.go
  cmd/idbtest/idbtest.go
  cmd/validator/core/dynamic_processor.go
  cmd/validator/core/struct_processor.go
  fetcher/fetcher.go
  idb/migration/migration.go
  idb/migration/migration_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  version/strings.go
Labels: tech debt, Team Carbon-11

#656 Inner transactions and logs support
  api/converter_utils.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_test.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/test_resources/app_call_inner.response
  api/test_resources/app_call_inner.txn
  api/test_resources/app_call_logs.response
  api/test_resources/app_call_logs.txn
  idb/postgres/internal/writer/writer.go
  idb/postgres/postgres_integration_test.go
Labels: Team Scytale

#665 Add missing dependencies: autoconf automake g++ boost-dev
  docker/Dockerfile
Labels: Unplanned, Team Carbon-11

#658 Handle request timeouts.
  api/server.go
Labels: Unplanned, Team Carbon-11

#661 Use ApplyData to fill asset/app idx on creation
  api/converter_utils.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_test.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/test_resources/app_call_inner.response
  api/test_resources/app_call_inner_acfg.response
  api/test_resources/app_call_inner_acfg.txn
  idb/postgres/internal/writer/writer.go
Labels: Team Scytale

#670 Improve postgres tests
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/postgres_rand_test.go
Labels: tech debt, Team Carbon-11

#674 Report error correctly
  api/middlewares/migration_middleware.go
Labels: bug, Team Carbon-11

#680 Do not compute pending rewards when rewinding
  accounting/rewind.go
  accounting/rewind_test.go
Labels: bug, Unplanned, Team Carbon-11

#675 Compute intra the same way TxnCounter increments.
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres_integration_test.go
  util/test/account_testutil.go
Labels: Unplanned, Team Carbon-11

#686 Always close resources
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
Labels: Team Carbon-11

#683 README.md - load balance configs
  README.md
Labels: Team Carbon-11

#687 Fix "conn busy" issue.
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_rand_test.go
Labels: bug, Team Carbon-11

#692 DO NOT MERGE: indexer 2.7.1
  .version
  README.md
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/internal/util/util.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_rand_test.go
Labels: Team Hyper Flow
