Repository algorand/indexer, pull requests merged in 2022-09, with the labels that each got.

#1211 build: Downgrade mockery to prevent incorrect deprecation warning.
  Makefile
  idb/mocks/IndexerDb.go
Labels: Bug-Fix

#1208 conduit: Convert daemon to conduit pipeline
  api/handlers.go
  api/server.go
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/daemon_test.go
  cmd/conduit/main.go
  conduit/pipeline.go
  conduit/pipeline_test.go
  fetcher/fetcher.go
  fetcher/fetcher_test.go
  util/pidfile.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1215 enhancement: adding ParticipationUpdates to response
  .gitignore
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  util/test/account_testutil.go
Labels: Enhancement

#1117 New Feature: Lookup Boxes by app-id + Name and Search Boxes by app-id
  .gitignore
  api/README.md
  api/app_boxes_fixtures_test.go
  api/error_messages.go
  api/fixtures_test.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/server.go
  api/test_resources/boxes.json
  cmd/algorand-indexer/daemon.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_random_box_test.go
  misc/parity/reports/algod2indexer_full.yml
  misc/parity/test_indexer_v_algod.py
  processor/eval/ledger_for_evaluator_test.go
  util/test/box_testutil.go
  util/test/programs.go
Labels: New Feature

#1233 conduit: Add filter_processor to all imports for processors
  processors/all/all.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1241 REST API: Add Header-Only parameter to blocks endpoint, return error if there are too many transactions.
  api/error_messages.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Enhancement, Team Lamprey
