Repository algorand/indexer, pull requests merged in 2022-06, with the labels that each got.

#1038 build: Lock to mockery minor version
  Makefile
Labels: Bug-Fix

#1037 docs: Add some missing options to the config mapping table.
  README.md
Labels: Enhancement, Team Lamprey

#1042 local ledger fixes
  cmd/algorand-indexer/daemon.go
  migrations/local_ledger/migration.go
  migrations/local_ledger/migration_test.go
  processor/blockprocessor/block_processor.go
Labels: Team Lamprey

#1034 FOR REVIEW ONLY: indexer 2.12.0 into develop
  .version
Labels: Enhancement, Team Hyper Flow

#1053 Bugfix: Correctly auto loads config file
  README.md
  cmd/algorand-indexer/daemon.go
Labels: Team Lamprey, Bug-Fix

#1057 Ignore: add test.txt file
  test.txt
Labels: Not-Yet-Enabled

#1060 DevOps: Add labels to Github Actions PR label check
  .github/workflows/pr-type-category.yml
Labels: Enhancement

#1065 Bug Fix: Fix auto-loading search
  README.md
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/main.go
  config/config.go
  docs/DisablingParametersGuide.md
Labels: Team Lamprey, Bug-Fix

#1072 DevOps: update dockerfile ubuntu from 18.04 to 20.04
  misc/docker/build.ubuntu.Dockerfile
Labels: Enhancement, Team Hyper Flow

#1075 Generate an error if the catchpoint is not valid for initialization.
  processor/blockprocessor/block_processor.go
  processor/blockprocessor/block_processor_test.go
Labels: Team Lamprey

#1077 Use main logger in handler and fetcher.
  processor/blockprocessor/initialize.go
  processor/blockprocessor/initialize_test.go
Labels: Team Lamprey

#1076 Switch from fullNode catchup to catchpoint catchup service.
  processor/blockprocessor/initialize.go
  processor/blockprocessor/initialize_test.go
  processor/blockprocessor/internal/catchupservice.go
Labels: Team Lamprey

#1073 FOR REVIEW ONLY: indexer 2.12.2 into master
  .github/workflows/pr-type-category.yml
  .version
  README.md
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/main.go
  config/config.go
  docs/DisablingParametersGuide.md
  misc/docker/build.ubuntu.Dockerfile
Labels: Skip-Release-Notes

#1074 FOR REVIEW ONLY: indexer 2.12.2 into develop
  .version
Labels: Team Hyper Flow, Skip-Release-Notes

#1080 Revert: update ubuntu from 18.04 to 20.04 (#1072)
  misc/docker/build.ubuntu.Dockerfile
Labels: Team Hyper Flow, Bug-Fix

#1078 Github-Actions: Updating pr label check
  .github/release.yml
  .github/workflows/pr-type-category.yml
Labels: Enhancement
