Repository algorand/indexer, pull requests merged in 2022-04, with the labels that each got.

#958 Cleanup README, add index management section, clarify transaction result order.
  README.md
  api/generated/v2/routes.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile.mule
  docker/run.sh
  docker/testdata.tar.bz2
  docs/PostgresqlIndexes.md
Labels: Team Lamprey

#957 vacuum doc
  docs/Vacuum.md
Labels: Team Lamprey

#966 Do not show block not found error after fetcher has finished catchup.
  cmd/algorand-indexer/main.go
  fetcher/fetcher.go
Labels: Team Lamprey

#965 Modified Rollback to occur before ctx
  idb/postgres/postgres.go
Labels: Team Lamprey

#974 Skip validator errors resulting from the account resource limit.
  api/converter_utils.go
  api/error_messages.go
  cmd/validator/core/command.go
  cmd/validator/core/validator.go
Labels: Team Lamprey

#983 CICD: Update build docker run command
  misc/Dockerfile
  misc/package_linux_arch.sh
Labels: Team Hyper Flow

#985 CICD: Adding PR Type label checker.
  .github/workflows/pr-type-category.yml
Labels: Enhancement, Team Lamprey
