Repository algorand/indexer, pull requests merged in 2022-05, with the labels that each got.

#988 DevOps: Merge back into dev 2.11.0
  .version
  api/error_messages.go
  api/handlers.go
  cmd/validator/core/command.go
  cmd/validator/core/validator.go
  misc/generate_accounts.sh
Labels: Enhancement, Team Hyper Flow

#981 Add system requirements to README.
  README.md
Labels: Enhancement, Team Lamprey

#990 Asset id check
  idb/postgres/postgres.go
Labels: Team Lamprey

#993 FOR REVIEW ONLY: indexer 2.11.1 into develop
  .version
Labels: Enhancement, Team Hyper Flow

#991 Developer Tools: create indexer data dir
  cmd/algorand-indexer/daemon.go
Labels: New Feature

#994 tests: Add tests for account asset amount validation.
  idb/postgres/postgres_integration_test.go
Labels: Enhancement, Team Lamprey

#995 CI: switch to codecov github action
  .circleci/config.yml
  .codecov.yml
  scripts/3rd_party/codecov
  scripts/upload_coverage.sh
Labels: Enhancement, Team Lamprey

#1000 ci: add version to golint install command.
  .circleci/config.yml
Labels: Team Lamprey, Bug-Fix

#1010 api: return empty lists from fetchApplications and fetchAppLocalStates
  api/handlers.go
Labels: Bug-Fix

#1005 api model: Update model to converge with algod
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
Labels: Bug-Fix
