Repository algorand/indexer, pull requests merged in 2022-07, with the labels that each got.

#1081 FOR REVIEW ONLY: indexer 2.12.3 into master
  .version
  misc/docker/build.ubuntu.Dockerfile
Labels: Team Hyper Flow, Skip-Release-Notes

#1069 RFC-0001: Rfc 0001 impl
  exporters/exporter.go
  exporters/exporter_factory.go
  exporters/exporter_factory_test.go
  exporters/noop/noop_exporter.go
  exporters/noop/noop_exporter_test.go
Labels: Enhancement

#1110 Misc Local Ledger PR feedback.
  api/handlers_e2e_test.go
  cmd/algorand-indexer/daemon_test.go
  cmd/import-validator/core/service.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  importer/helper.go
  processor/blockprocessor/block_processor.go
  processor/blockprocessor/block_processor_test.go
  processor/blockprocessor/initialize.go
  processor/blockprocessor/internal/catchupservice.go
  processor/eval/ledger_for_evaluator.go
  processor/eval/ledger_for_evaluator_test.go
Labels: Team Lamprey

#1114 Conduit: Postgres exporter initial implementation
  data/block_export_data.go
  exporters/exporter.go
  exporters/exporter_factory.go
  exporters/exporter_factory_test.go
  exporters/metadata.go
  exporters/noop/noop_exporter.go
  exporters/noop/noop_exporter_test.go
  exporters/postgresql/postgresql_exporter.go
  exporters/postgresql/postgresql_exporter_config.go
  exporters/postgresql/postgresql_exporter_test.go
  idb/dummy/dummy.go
  idb/dummy/dummy_factory.go
  plugins/config.go
  plugins/config_test.go
  plugins/metadata.go
Labels: New Feature

#1136 Conduit: Add all PluginTypes
  plugins/metadata.go
Labels: Not-Yet-Enabled

#1125 Documentation for data directory.
  README.md
  docs/DataDirectory.md
Labels: Team Lamprey

#1146 Enhancement: remove import validator utility and obsolete ledger for evaluator
  cmd/algorand-indexer/main.go
  cmd/import-validator/README.md
  cmd/import-validator/core/command.go
  cmd/import-validator/core/service.go
  cmd/import-validator/main.go
  go.mod
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_rand_test.go
Labels: Enhancement

#1138 FOR REVIEW ONLY: indexer 2.13.0 into develop
  .version
  README.md
  accounting/eval_preload.go
  api/server.go
  cmd/block-generator/generator/generate.go
  cmd/block-generator/run_tests.sh
  cmd/block-generator/runner/run.go
  cmd/block-generator/runner/runner.go
  docs/DataDirectory.md
Labels: Skip-Release-Notes

#1149 Docs: Readme update
  README.md
  docs/assets/algorand_logo_mark_black.svg
  docs/assets/algorand_logo_mark_white.svg
Labels: documentation, Skip-Release-Notes

#1152 Testing: Use tempdir instead of /tmp for e2elive test
  misc/e2elive.py
  misc/util.py
Labels: Team Lamprey, Skip-Release-Notes

#1153 Enhancement: Format misc/*.py with `black`
  misc/blockarchiver.py
  misc/liveindextest.py
  misc/release.py
  misc/speedtest.py
  misc/util.py
  misc/validate_accounting.py
Labels: Enhancement

#1154 Enhancement: apply black to e2elive.py as well
  misc/e2elive.py
Labels: Enhancement
