Repository algorand/indexer, pull requests merged in 2022-11, with the labels that each got.

#1301 conduit: fix e2e_conduit
  Makefile
  e2e_tests/src/e2e_conduit/fixtures/importers/algod.py
Labels: Team Lamprey

#1298 conduit: plugin constructor
  docs/conduit/Development.md
  exporters/example/example_exporter.go
  exporters/example/example_exporter_test.go
  exporters/exporter_factory.go
  exporters/filewriter/file_exporter.go
  exporters/filewriter/file_exporter_test.go
  exporters/noop/noop_exporter.go
  exporters/noop/noop_exporter_test.go
  exporters/postgresql/postgresql_exporter.go
  exporters/postgresql/postgresql_exporter_test.go
  importers/algod/algod_importer.go
  importers/filereader/filereader.go
  importers/importer.go
  importers/importer_factory.go
  processors/blockprocessor/block_processor.go
  processors/filterprocessor/filter_processor.go
  processors/noop/noop_processor.go
  processors/processor_factory.go
Labels: Team Lamprey

#1287 Adding a link to the data directory documentation
  README.md
Labels: documentation, Enhancement

#1316 Tests: cleanup
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
Labels: Skip-Release-Notes

#1324 Ignore no op asset transfers.
  accounting/eval_preload.go
Labels: Bug-Fix

#1358 lint: Fix errors showing up w/ golanci-lint
  conduit/errors.go
  conduit/pipeline/pipeline.go
  conduit/plugins/exporters/postgresql/util/prune.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/importer.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/initialize.go
  conduit/plugins/processors/filterprocessor/fields/filter.go
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  idb/dummy/dummy.go
  util/metrics/metrics.go
  util/test/mock_algod.go
  util/test/testutil.go
  util/util.go
Labels: Skip-Release-Notes
