Repository algorand/indexer, pull requests merged in 2022-02, with the labels that each got.

#865 block-generator: Add README.
  cmd/block-generator/README.md
Labels: Team Lamprey

#866 Adding slack notifications to builds
  .circleci/config.yml
Labels: Team Hyper Flow

#867 Add default and max limits for applications endpoint.
  api/handlers.go
  api/handlers_test.go
Labels: Team Lamprey

#864 block-generator: Improve payment algorithm to allow sending many more transactions.
  cmd/block-generator/generator/generate.go
  cmd/block-generator/generator/make_transactions.go
  cmd/block-generator/run_runner.sh
Labels: Team Lamprey

#820 Return Inner and Root transactions for nested logs support in C2C calls
  api/converter_utils.go
  api/handlers.go
  api/handlers_e2e_test.go
  go.sum
  idb/idb.go
  idb/idb_test.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/writer/write_txn.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  util/test/account_testutil.go
Labels: Team Scytale

#880 Fix log permissions to not be executable.
  cmd/algorand-indexer/main.go
Labels: Unplanned, Team Hyper Flow

#876 monitoring dashboard
  cmd/algorand-indexer/daemon.go
  fetcher/fetcher.go
  monitoring/Dockerfile-indexer
  monitoring/README.md
  monitoring/dashboard.json
  monitoring/docker-compose.yml
  monitoring/examples/widgets.png
  monitoring/grafana.ini
  monitoring/grafana_prometheus_datasource.yml
  monitoring/prometheus.yml
  util/metrics/metrics.go
Labels: Team Lamprey
