Repository algorand/indexer, pull requests merged in 2022-08, with the labels that each got.

#1151 Enhancement: More information about S3 keys searched for and Dockerfile that uses submodule instead of channel
  misc/Dockerfile
  misc/e2elive.py
  misc/util.py
Labels: Enhancement

#1157 Conduit: Merge conduit develop
  .version
  README.md
  accounting/eval_preload.go
  api/server.go
  cmd/algorand-indexer/main.go
  cmd/block-generator/generator/generate.go
  cmd/block-generator/run_tests.sh
  cmd/block-generator/runner/run.go
  cmd/block-generator/runner/runner.go
  cmd/import-validator/README.md
  cmd/import-validator/core/command.go
  cmd/import-validator/core/service.go
  cmd/import-validator/main.go
  docs/DataDirectory.md
  docs/assets/algorand_logo_mark_black.svg
  docs/assets/algorand_logo_mark_white.svg
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator.go
  idb/postgres/internal/ledger_for_evaluator/ledger_for_evaluator_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_rand_test.go
  misc/Dockerfile
  misc/blockarchiver.py
  misc/e2elive.py
  misc/liveindextest.py
  misc/release.py
  misc/speedtest.py
  misc/util.py
  misc/validate_accounting.py
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1135 Conduit: Algod importer implementation
  docs/rfc/0003-importer-interface.md
  importers/algod/algod_importer.go
  importers/algod/algod_importer_config.go
  importers/algod/algod_importer_test.go
  importers/importer.go
  importers/metadata.go
Labels: Team Lamprey, New Feature

#1162 Bug-Fix: Revert to Eric's Original BlockHdrCached implementation + miscellany
  .gitignore
  Makefile
  misc/Dockerfile
  misc/docker-compose.yml
  misc/e2elive.py
  processor/eval/ledger_for_evaluator.go
Labels: Bug-Fix

#1166 Enhancement: add max int64 checks
  api/error_messages.go
  api/handlers.go
  api/handlers_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Enhancement, Team Lamprey

#1176 Use config to control noop exporter round start
  exporters/noop/noop_exporter.go
  exporters/noop/noop_exporter_config.go
  exporters/noop/noop_exporter_test.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1177 Set pgsql exporter round from db on init
  exporters/postgresql/postgresql_exporter.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1178 Add waits/retries to algod importer
  .codecov.yml
  fetcher/fetcher_test.go
  importers/algod/algod_importer.go
  importers/algod/algod_importer_test.go
  util/test/mock_algod.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1180 Stop Panics if no config is supplied
  cmd/algorand-indexer/api_config.go
Labels: Bug-Fix

#1186 Disable deadlock detection
  cmd/algorand-indexer/main.go
  util/disabledeadlock/disable_deadlock.go
Labels: bug

#1183 conduit: pipeline run loop implementation
  conduit/logging.go
  conduit/pipeline.go
  exporters/postgresql/postgresql_exporter.go
  importers/algod/algod_importer.go
  processors/blockprocessor/block_processor.go
  processors/blockprocessor/block_processor_test.go
  processors/noop/noop_processor.go
  processors/processor.go
  processors/processor_factory.go
  processors/processor_factory_test.go
Labels: Team Lamprey, Not-Yet-Enabled, Skip-Release-Notes

#989 Add support for new block header: TxnRoot SHA256
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
  api/test_resources/stpf_block_response.json
Labels: Enhancement

#1181 Config: Accept yaml and yml configuration files.
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/daemon_test.go
  cmd/algorand-indexer/main.go
  config/config.go
Labels: New Feature

#1198 Bug: Fix bug in reveals lookup
  api/converter_utils.go
Labels: Bug-Fix

#1199 Testing: Add a sample state proof with high index for testing
  api/handlers_test.go
  api/test_resources/state_proof_with_index.response
  api/test_resources/state_proof_with_index.txn
  api/test_resources/stpf_block_high_index.block
  api/test_resources/stpf_block_high_index_response.json
Labels: Enhancement

#1204 conduit bugfix: succeed close calls when init fails
  exporters/postgresql/postgresql_exporter.go
  importers/algod/algod_importer.go
  processors/blockprocessor/block_processor.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1205 conduit bugfix: silence usage data on error
  cmd/conduit/main.go
Labels: Not-Yet-Enabled, Skip-Release-Notes

#1201 enhancement: Clarify REST query parameters for accounts search
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/indexer.oas2.json
  api/indexer.oas3.yml
Labels: Enhancement

#1169 cicd: add darwin arm64 support to release script
  misc/release.py
Labels: Skip-Release-Notes
