Repository algorand/indexer, pull requests merged in 2022-01, with the labels that each got.

#817 Better context usage
  accounting/rewind.go
  accounting/rewind_test.go
  api/handlers.go
  api/middlewares/migration_middleware.go
  api/middlewares/migration_middleware_test.go
  cmd/idbtest/idbtest.go
  go.mod
  go.sum
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
Labels: Unplanned, Team Carbon-11

#823 Add retry loop to block handler.
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/daemon_test.go
  importer/helper.go
  importer/importer.go
Labels: Team Lamprey

#833 Add startup check to verify existing DB data matches the algod network.
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/schema/metastate.go
  idb/postgres/internal/types/types.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Team Lamprey

#841 Reverting golang 1.16 upgrade
  .circleci/config.yml
  Makefile
  README.md
  cmd/block-generator/docker/Dockerfile-generator
  cmd/block-generator/docker/Dockerfile-indexer
  go.mod
  misc/Dockerfile
Labels: Team Hyper Flow

#840 Remove duplicate inner transactions from blocks endpoint.
  api/handlers.go
  api/handlers_e2e_test.go
Labels: Team Lamprey

#837 Changed configuration for postgres
  README.md
  cmd/algorand-indexer/daemon.go
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Team Lamprey

#853 Add additional encoding tests.
  api/handlers.go
  api/handlers_e2e_test.go
  cmd/validator/core/validator.go
  util/util_test.go
Labels: Team Lamprey

#842 add genesis hash check to import
  cmd/algorand-indexer/daemon.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  importer/helper.go
Labels: Team Lamprey

#856 Fix network validation during database upgrade case.
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  importer/helper.go
Labels: bug, Team Lamprey
