Repository algorand/indexer, pull requests merged in 2022-03, with the labels that each got.

#904 Fix bad merge.
  idb/postgres/postgres.go
Labels: Team Lamprey

#906 Document instructions for updating Indexer E2E test input
  misc/README.md
  test/README.md
Labels: Team Scytale

#915 Don't do deduplication based on txID when returning inner transactions
  api/handlers.go
  api/handlers_e2e_test.go
  util/test/account_testutil.go
Labels: Team Scytale

#927 Validator: Fix processorNum variable.
  cmd/validator/core/command.go
Labels: Team Lamprey, Bug-Fix

#921 Tests: Elaboration on system configuration for E2E tests
  misc/README.md
Labels: Enhancement, Team Scytale

#937 Ensure block-generator service shutdown after failure.
  cmd/block-generator/runner/run.go
Labels: Team Lamprey

#933 Set max account API resource limit to 1000.
  api/handlers_e2e_test.go
  cmd/algorand-indexer/daemon.go
  idb/postgres/postgres.go
  test/README.md
  test/common.sh
Labels: Team Lamprey

#935 Consider TxType when selecting transaction amount currency type.
  api/converter_utils.go
  api/handlers_test.go
Labels: Team Lamprey
