Repository algorand/indexer, pull requests merged in 2022-12, with the labels that each got.

#1354 Tests: Fix e2e tests
  .circleci/config.yml
Labels: Bug-Fix

#1364 Bug-Fix: pass failing `nightly_test_indexer_vs_algod`
  .circleci/config.yml
Labels: Bug-Fix

#1353 metrics: Configurable conduit metrics prefix.
  cmd/algorand-indexer/main.go
  cmd/conduit/main.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  fetcher/fetcher_test.go
  util/metrics/metrics.go
Labels: Enhancement

#1357 conduit: Pass data dir to plugin config.
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/config.go
  conduit/plugins/exporters/example/example_exporter.go
  conduit/plugins/exporters/example/example_exporter_test.go
  conduit/plugins/exporters/exporter.go
  conduit/plugins/exporters/filewriter/file_exporter.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/exporters/noop/noop_exporter.go
  conduit/plugins/exporters/noop/noop_exporter_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_config.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/importers/importer.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/filterprocessor/sample_test.go
  conduit/plugins/processors/noop/noop_processor.go
  conduit/plugins/processors/processor.go
Labels: Enhancement

#1367 conduit: Move eval package into blockprocessor.
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/internal/eval/ledger_for_evaluator.go
  conduit/plugins/processors/blockprocessor/internal/eval/ledger_for_evaluator_test.go
Labels: Team Lamprey, Skip-Release-Notes

#1352 tech debt: Indexer initialization improvements
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/daemon_test.go
  cmd/algorand-indexer/import.go
  cmd/algorand-indexer/main.go
Labels: Bug-Fix

#1366 conduit: Default to plugin data directory when possible.
  conduit/plugins/exporters/filewriter/file_exporter.go
  conduit/plugins/exporters/filewriter/file_exporter_config.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/exporters/filewriter/sample.yaml
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/config.go
  conduit/plugins/processors/blockprocessor/config_test.go
  conduit/plugins/processors/blockprocessor/initialize.go
  conduit/plugins/processors/blockprocessor/initialize_test.go
  conduit/plugins/processors/blockprocessor/sample.yaml
  docs/conduit/plugins/block_evaluator.md
  docs/conduit/plugins/file_writer.md
Labels: Enhancement

#1369 Conduit: Simplify and fix Conduit init.
  cmd/algorand-indexer/daemon.go
  cmd/conduit/main.go
  conduit/config.go
  conduit/config_test.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/processors/blockprocessor/config_test.go
  loggers/loggers.go
  loggers/loggers_test.go
  util/util.go
Labels: Team Lamprey, Skip-Release-Notes

#1370 New Feature: Add Retry Variables
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
Labels: Team Lamprey, New Feature

#1377 conduit: Add version flag to conduit root command.
  Makefile
  cmd/algorand-indexer/main.go
  cmd/conduit/main.go
Labels: Enhancement

#1376 conduit: Fix init template and allow plugins which have empty config.
  cmd/conduit/conduit.yml.example
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
Labels: Skip-Release-Notes

#1379 Conduit: Adds strict unmarshalling
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
Labels: New Feature

#1380 conduit: Added retry variables for daemon run
  cmd/algorand-indexer/daemon.go
Labels: Bug-Fix

#1334 enhancement: refactor idb module
  accounting/accounting.go
  accounting/rewind.go
  accounting/rewind_test.go
  api/converter_utils.go
  api/handlers.go
  api/handlers_test.go
  api/pointer_utils.go
  cmd/e2equeries/main.go
  go.mod
  go.sum
  helpers/helpers.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/idb_test.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/encoding/types.go
  idb/postgres/internal/writer/write_txn.go
  idb/postgres/internal/writer/write_txn_participation.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_rand_test.go
  idb/sig_type.go
  idb/txn_type_enum.go
  types/types.go
  util/test/account_testutil.go
  util/util.go
  util/util_test.go
Labels: Enhancement

#1371 Docs: Improve Conduit documentation.
  docs/Conduit.md
  docs/conduit/GettingStarted.md
  docs/conduit/tutorials/FilterDeepDive.md
  docs/conduit/tutorials/IndexerMigration.md
  docs/conduit/tutorials/WritingBlocksToFile.md
  docs/rfc/template.md
  e2e_tests/src/e2e_conduit/runner.py
  e2e_tests/src/e2e_conduit/scenarios/__init__.py
Labels: Enhancement

#1385 enhancement: refactor bookkeeping.genesis import
  api/fixtures_test.go
  api/handlers_e2e_test.go
  cmd/block-generator/generator/generate.go
  conduit/init_provider.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/importers/importer.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/config_test.go
  data/block_export_data.go
  go.mod
  go.sum
  helpers/helpers.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/types/types.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_rand_test.go
  importer/helper.go
  importer/importer.go
  protocol/config/config.go
  protocol/consensus.go
  util/ledger_util.go
  util/test/account_testutil.go
  util/test/testutil.go
Labels: Enhancement, Team Lamprey

#1389 encoding: Use LenientDecode for genesis objects from algod
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/filereader/filereader.go
  util/test/mock_algod.go
  util/util.go
  util/util_test.go
Labels: Bug-Fix

#1382 docs: Docs automation
  .gitignore
  Makefile
  cmd/conduit-docs/README.md
  cmd/conduit-docs/main.go
  cmd/conduit/main.go
  conduit/plugins/exporters/filewriter/file_exporter_config.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_config.go
  conduit/plugins/importers/algod/algod_importer_config.go
  conduit/plugins/importers/filereader/filereader_config.go
  conduit/plugins/processors/blockprocessor/config.go
  conduit/plugins/processors/filterprocessor/config.go
Labels: Skip-Release-Notes

#1390 REST API: Add compression to REST API
  api/handlers_e2e_test.go
  api/server.go
Labels: New Feature

#1394 REST API: Add compression to REST API (#1390)
  api/handlers_e2e_test.go
  api/server.go
Labels: Bug-Fix
