Repository algorand/indexer, pull requests merged in 2023-03, with the labels that each got.

#1488 file-exporter: Use strict encoding when writing files.
  conduit/plugins/exporters/filewriter/file_exporter.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_test.go
  util/util.go
  util/util_test.go
Labels: Bug-Fix

#1487 filter-plugin: Inner Txn support.
  .codecov.yml
  conduit/plugins/processors/filterprocessor/config.go
  conduit/plugins/processors/filterprocessor/expression/expression.go
  conduit/plugins/processors/filterprocessor/expression/expression_test.go
  conduit/plugins/processors/filterprocessor/expression/numerical_expressions.go
  conduit/plugins/processors/filterprocessor/fields/filter.go
  conduit/plugins/processors/filterprocessor/fields/generated_signed_txn_map.go
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/fields/searcher_test.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
  docs/conduit/plugins/filter_processor.md
Labels: Enhancement

#1485 importer: rewrite make integration
  .circleci/config.yml
  Makefile
  api/handlers_e2e_test.go
  api/test_resources/validated_blocks/Accounts1.vb
  api/test_resources/validated_blocks/Accounts2.vb
  api/test_resources/validated_blocks/Accounts3.vb
  api/test_resources/validated_blocks/Accounts4.vb
  api/test_resources/validated_blocks/Accounts5.vb
  api/test_resources/validated_blocks/AppDelete.vb
  api/test_resources/validated_blocks/ApplicationLocal1.vb
  api/test_resources/validated_blocks/ApplicationLocal2.vb
  api/test_resources/validated_blocks/ApplicationLocal3.vb
  api/test_resources/validated_blocks/ApplicationLocal4.vb
  api/test_resources/validated_blocks/ApplicationLocal5.vb
  api/test_resources/validated_blocks/ApplicationLocal6.vb
  api/test_resources/validated_blocks/ApplicationLocal7.vb
  api/test_resources/validated_blocks/ApplicationLocal8.vb
  api/test_resources/validated_blocks/ApplicationLocal9.vb
  api/test_resources/validated_blocks/AssetDelete.vb
  api/test_resources/validated_blocks/AssetHoldings1.vb
  api/test_resources/validated_blocks/AssetHoldings2.vb
  api/test_resources/validated_blocks/AssetHoldings3.vb
  api/test_resources/validated_blocks/AssetHoldings4.vb
  api/test_resources/validated_blocks/AssetHoldings5.vb
  api/test_resources/validated_blocks/AssetHoldings6.vb
  api/test_resources/validated_blocks/AssetHoldings7.vb
  api/test_resources/validated_blocks/AssetHoldings8.vb
  cmd/algorand-indexer/import.go
  cmd/algorand-indexer/main.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  idb/postgres/postgres_integration_test.go
  importer/helper.go
  importer/importer.go
  test/postgres_integration_test.sh
  util/util.go
Labels: Enhancement, Team Lamprey

#1484 refactor: Remove blockprocessor, algorand-indexer import cmd
  accounting/eval_preload.go
  accounting/rewind_test.go
  conduit/plugins/processors/all/all.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/block_processor_test.go
  conduit/plugins/processors/blockprocessor/config.go
  conduit/plugins/processors/blockprocessor/config_test.go
  conduit/plugins/processors/blockprocessor/initialize.go
  conduit/plugins/processors/blockprocessor/initialize_test.go
  conduit/plugins/processors/blockprocessor/internal/catchupservice.go
  conduit/plugins/processors/blockprocessor/internal/catchupservice_test.go
  conduit/plugins/processors/blockprocessor/internal/eval/ledger_for_evaluator.go
  conduit/plugins/processors/blockprocessor/internal/eval/ledger_for_evaluator_test.go
  conduit/plugins/processors/blockprocessor/metrics.go
  conduit/plugins/processors/blockprocessor/sample.yaml
  data/block_export_data.go
  e2e_tests/src/e2e_conduit/e2econduit.py
  e2e_tests/src/e2e_conduit/fixtures/processors/__init__.py
  e2e_tests/src/e2e_conduit/fixtures/processors/block_evaluator.py
  e2e_tests/src/e2e_conduit/scenarios/follower_indexer_scenario.py
  e2e_tests/src/e2e_conduit/scenarios/indexer_scenario.py
  fetcher/fetcher.go
  fetcher/fetcher_test.go
  idb/idb.go
  idb/postgres/postgres.go
Labels: Skip-Release-Notes

#1490 testutil: remove go-algorand reference
  api/fixtures_test.go
  api/handlers_e2e_test.go
  idb/idb_test.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations_test.go
  idb/postgres/postgres_rand_test.go
  util/test/account_testutil.go
  util/test/testutil.go
Labels: Enhancement, Team Lamprey

#1491 chore: remove more go-algorand refs
  conduit/gen/lookup.go
  conduit/plugins/processors/filterprocessor/expression/numerical_expressions.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
  helpers/helpers.go
  util/metrics/metrics.go
Labels: Enhancement, Team Lamprey

#1489 conduit: Reorganize ahead of repo split.
  accounting/accounting.go
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/main.go
  cmd/conduit/main.go
  conduit/data/block_export_data.go
  conduit/hooks.go
  conduit/loggers/loggers.go
  conduit/loggers/loggers_test.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/exporters/example/example_exporter.go
  conduit/plugins/exporters/example/example_exporter_test.go
  conduit/plugins/exporters/exporter.go
  conduit/plugins/exporters/filewriter/file_exporter.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/exporters/filewriter/util.go
  conduit/plugins/exporters/filewriter/util_test.go
  conduit/plugins/exporters/noop/noop_exporter.go
  conduit/plugins/exporters/noop/noop_exporter_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/mock_algod_test.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/importers/importer.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/noop/noop_processor.go
  conduit/plugins/processors/processor.go
  conduit/plugins/tools/testutil/mockinit.go
  config/datadir.go
  config/datadir_test.go
  idb/postgres/internal/writer/write_txn_participation.go
  util/disabledeadlock/disable_deadlock.go
  util/test/testutil.go
  util/util.go
  util/util_test.go
Labels: Enhancement, Team Lamprey

#1497 logging: Clean up conduit init logging.
  cmd/conduit/main.go
  cmd/conduit/main_test.go
  conduit/pipeline/pipeline.go
Labels: Enhancement, Team Lamprey

#1498 refactoring: Move init command into a separate internal package.
  cmd/conduit/internal/initialize/conduit.test.init.default.yml
  cmd/conduit/internal/initialize/conduit.yml.example
  cmd/conduit/internal/initialize/init.go
  cmd/conduit/internal/initialize/init_test.go
  cmd/conduit/main.go
  cmd/conduit/main_test.go
Labels: Enhancement

#1493 e2e-tests: Filter processor e2e test
  e2e_tests/README.md
  e2e_tests/src/e2e_conduit/e2econduit.py
  e2e_tests/src/e2e_conduit/fixtures/processors/__init__.py
  e2e_tests/src/e2e_conduit/fixtures/processors/filter.py
  e2e_tests/src/e2e_conduit/scenarios/filter_scenario.py
  e2e_tests/src/e2e_indexer/e2elive.py
Labels: Enhancement

#1503 e2e-tests: Add filtered indexer e2e tests
  .circleci/config.yml
  Makefile
  e2e_tests/docker/indexer-filtered/docker-compose.yml
  e2e_tests/docker/indexer-filtered/e2e-read/Dockerfile
  e2e_tests/docker/indexer-filtered/e2e-write/Dockerfile
  e2e_tests/docker/indexer-filtered/e2e-write/conduit.yml
  e2e_tests/pyproject.toml
  e2e_tests/src/e2e_common/get_test_data.py
  e2e_tests/src/e2e_indexer/e2elive.py
Labels: Enhancement
