Repository algorand/indexer, pull requests merged in 2023-06, with the labels that each got.

#1541 chore: Add Goreleaser/Docker image builds
  .gitignore
  .goreleaser.yaml
  Dockerfile
  Makefile
  docker/docker-entrypoint.sh
  version/strings.go
Labels: Enhancement

#1542 chore: Goreleaser deb
  .goreleaser.yaml
Labels: Enhancement

#1544 api: Omit asset params from acfg delete txns
  api/converter_utils.go
  api/handlers_e2e_test.go
Labels: Bug-Fix

#1543 api: Convert timezones before txn query
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_test.go
Labels: Bug-Fix

#1546 chore: update CI config
  .circleci/config.yml
Labels: Enhancement, Team Lamprey

#1551 chore: Update go-algorand-sdk
  api/converter_utils.go
  go.mod
  go.sum
Labels: Skip-Release-Notes

#1552 chore: Bump module path
  accounting/rewind.go
  accounting/rewind_test.go
  api/app_boxes_fixtures_test.go
  api/converter_utils.go
  api/disabled_parameters_test.go
  api/error_messages.go
  api/fixtures_test.go
  api/generated/common/routes.go
  api/generated/common/types.go
  api/generated/v2/routes.go
  api/generated/v2/types.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/middlewares/migration_middleware.go
  api/middlewares/migration_middleware_test.go
  api/server.go
  api/util_test.go
  cmd/algorand-indexer/api_config.go
  cmd/algorand-indexer/daemon.go
  cmd/algorand-indexer/daemon_test.go
  cmd/algorand-indexer/main.go
  cmd/e2equeries/main.go
  cmd/idbtest/idbtest.go
  cmd/validator/core/struct_processor.go
  cmd/validator/core/validator.go
  cmd/validator/core/validator_test.go
  cmd/validator/main.go
  go.mod
  go.sum
  idb/dummy/dummy.go
  idb/dummy/dummy_factory.go
  idb/idb.go
  idb/idb_test.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/migrations/convert_account_data/m.go
  idb/postgres/internal/migrations/convert_account_data/m_test.go
  idb/postgres/internal/testing/testing.go
  idb/postgres/internal/util/util.go
  idb/postgres/internal/util/util_test.go
  idb/postgres/internal/writer/write_txn.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_factory.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_migrations.go
  idb/postgres/postgres_migrations_test.go
  idb/postgres/postgres_rand_test.go
  idb/postgres/postgres_test.go
  idb/postgres/testing/pgtest.go
  util/test/account_testutil.go
  util/test/testutil.go
  util/util.go
Labels: Skip-Release-Notes

#1553 v3: Initial commit of release
  .github/workflows/goreleaser.yml
Labels: Skip-Release-Notes

#1556 chore: Mergeback changes from v3
  .github/workflows/goreleaser.yml
Labels: Skip-Release-Notes
