Repository algorand/indexer, pull requests merged in 2023-01, with the labels that each got.

#1397 API: Hotfix block endpoint
  api/handlers.go
  idb/idb.go
  idb/postgres/postgres.go
Labels: Bug-Fix

#1402 API: Skip inner transaction fetching when possible.
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_test.go
Labels: Enhancement, Team Lamprey

#1400 FOR REVIEW ONLY: indexer 2.15.1 into master
  .version
  api/handlers.go
  api/handlers_e2e_test.go
  api/server.go
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_test.go
Labels: Skip-Release-Notes

#1412 tests: Add a way to pause the e2e docker container for debugging.
  Makefile
  e2e_tests/docker/indexer/Dockerfile
  e2e_tests/docker/indexer/docker-compose.yml
  e2e_tests/src/e2e_indexer/e2elive.py
Labels: Enhancement

#1401 FOR REVIEW ONLY: indexer 2.15.1 into develop
  .version
  api/handlers.go
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_test.go
Labels: Skip-Release-Notes

#1409 avm-abi: Switch from logic package to avm-abi library
  api/app_boxes_fixtures_test.go
  api/handlers.go
  api/handlers_e2e_test.go
  conduit/plugins/processors/blockprocessor/internal/eval/ledger_for_evaluator_test.go
  go.mod
  go.sum
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres_boxes_test.go
Labels: Enhancement

#1417 db: Remove AccountTotals from metastate
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/schema/metastate.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
Labels: Enhancement

#1423 dependencies: Upgrade go SDK to v2.
  accounting/accounting.go
  accounting/rewind.go
  accounting/rewind_test.go
  api/converter_utils.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/pointer_utils.go
  cmd/block-generator/generator/generate.go
  cmd/e2equeries/main.go
  cmd/idbtest/idbtest.go
  cmd/validator/core/validator.go
  cmd/validator/core/validator_test.go
  conduit/init_provider.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/filereader/filereader.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/importers/importer.go
  conduit/plugins/processors/blockprocessor/config_test.go
  conduit/plugins/processors/blockprocessor/initialize_test.go
  data/block_export_data.go
  fetcher/fetcher.go
  go.mod
  go.sum
  helpers/helpers.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/idb_test.go
  idb/mocks/IndexerDb.go
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/encoding/types.go
  idb/postgres/internal/types/types.go
  idb/postgres/internal/writer/write_txn.go
  idb/postgres/internal/writer/write_txn_participation.go
  idb/postgres/internal/writer/writer.go
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_rand_test.go
  idb/sig_type.go
  idb/txn_type_enum.go
  importer/helper.go
  misc/convertToAddress.go
  types/types.go
  util/ledger_util.go
  util/ledger_util_test.go
  util/test/account_testutil.go
  util/test/mock_algod.go
  util/test/testutil.go
  util/util.go
  util/util_test.go
Labels: Enhancement, Team Lamprey

#1424 enhancement: more integration test refactoring
  api/app_boxes_fixtures_test.go
  api/fixtures_test.go
  api/handlers_e2e_test.go
  api/test_resources/validated_blocks/AccountClearsNonUTF8.vb
  api/test_resources/validated_blocks/AccountExcludeParameters.vb
  api/test_resources/validated_blocks/AccountMaxResultsLimit.vb
  api/test_resources/validated_blocks/ApplicationHandlers.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete1.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete2.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete3.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete4.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete5.vb
  api/test_resources/validated_blocks/BoxCreateMutateDelete6.vb
  api/test_resources/validated_blocks/FetchBlockWithExpiredPartAccts.vb
  api/test_resources/validated_blocks/FetchBlockWithOptions.vb
  api/test_resources/validated_blocks/GetBlockWithCompression.vb
  api/test_resources/validated_blocks/GetBlocksTransactionsLimit10.vb
  api/test_resources/validated_blocks/GetBlocksTransactionsLimit2.vb
  api/test_resources/validated_blocks/GetBlocksTransactionsLimit20.vb
  api/test_resources/validated_blocks/InnerTxn.vb
  api/test_resources/validated_blocks/KeyregTransactionWithStateProofKeys.vb
  api/test_resources/validated_blocks/LiveBoxesR1.vb
  api/test_resources/validated_blocks/LiveBoxesR2.vb
  api/test_resources/validated_blocks/LiveBoxesR3.vb
  api/test_resources/validated_blocks/LiveBoxesR4.vb
  api/test_resources/validated_blocks/LiveBoxesR5.vb
  api/test_resources/validated_blocks/LiveBoxesR6.vb
  api/test_resources/validated_blocks/LiveBoxesR7.vb
  api/test_resources/validated_blocks/LiveBoxesR8.vb
  api/test_resources/validated_blocks/LiveBoxesR9.vb
  api/test_resources/validated_blocks/LookupInnerLogs.vb
  api/test_resources/validated_blocks/LookupMultiInnerLogs.vb
  api/test_resources/validated_blocks/PagingRootTxnDeduplication.vb
  go.sum
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_rand_test.go
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR1.vb
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR2.vb
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR3.vb
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR4.vb
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR5.vb
  idb/postgres/test_resources/validated_blocks/BoxCreateMutateDeleteR6.vb
Labels: Enhancement, Team Lamprey

#1436 bugfix: Reject empty genesis file.
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  util/test/mock_algod.go
Labels: Bug-Fix

#1418 tech debt: Rename and simplify app log transactions query.
  api/converter_utils.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/util_test.go
  idb/idb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_integration_test.go
  idb/postgres/postgres_test.go
Labels: Enhancement

#1442 local ledger: Ignore duplicate genesis block adds.
  idb/postgres/postgres.go
Labels: Bug-Fix

#1443 FOR REVIEW ONLY: indexer 2.15.3 into master
  .version
  idb/postgres/postgres.go
Labels: Skip-Release-Notes

#1445 build: Fix lint/vet
  api/handlers_e2e_test.go
  api/util_test.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
Labels: Bug-Fix

#1447 algodfollower: Fix genesis file parsing and error handling.
  conduit/plugins/importers/algodfollower/algodfollower_importer.go
  conduit/plugins/importers/algodfollower/algodfollower_importer_test.go
Labels: Team Lamprey, Bug-Fix

#1446 docs: Remove extra conduit-docs output.
  cmd/conduit-docs/main.go
Labels: Enhancement, Team Lamprey

#1378 Conduit: use correct subsystem in plugin metrics.
  cmd/algorand-indexer/daemon.go
  conduit/config.go
  conduit/hooks.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/metrics.go
  conduit/plugins/importers/algodfollower/algodfollower_importer.go
  conduit/plugins/importers/algodfollower/algodfollower_importer_test.go
  conduit/plugins/importers/algodfollower/metrics.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/initialize_test.go
  conduit/plugins/processors/blockprocessor/metrics.go
  docs/conduit/Development.md
Labels: Team Lamprey, Skip-Release-Notes

#1448 Bug Fix: Supported Disabled option
  conduit/plugins/exporters/postgresql/util/prune.go
  conduit/plugins/exporters/postgresql/util/prune_test.go
Labels: Bug-Fix
