Repository algorand/indexer, pull requests merged in 2023-05, with the labels that each got.

#1520 DevOps: Add CODEOWNERS to protect workflows directories
  .github/workflows/pr-type-category.yml
  CODEOWNERS
Labels: Enhancement, Team Hyper Flow

#1524 alerting: Slack `#lamprey-builds` Channel
  .circleci/config.yml
Labels: Skip-Release-Notes

#1527 chore: update codeowners
  CODEOWNERS
Labels: Enhancement, Team Lamprey

#1512 Docs: fix typo in oas file
  api/indexer.oas2.json
  api/indexer.oas3.yml
Labels: Bug-Fix

#1532 tests: Fix tests with app and asset ID less than 1000.
  api/app_boxes_fixtures_test.go
  api/handlers_e2e_test.go
  api/test_resources/boxes.json
  idb/postgres/internal/writer/writer_test.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_test.go
  processor/eval/ledger_for_evaluator_test.go
Labels: Team Lamprey

#1534 community: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Skip-Release-Notes

#1523 Enhancement: more logging in E2E tests + turn back on commit-workflow E2E test
  .circleci/config.yml
  api/README.md
  cmd/validator/core/command.go
  docs/PostgresqlIndexes.md
  e2e_tests/README.md
  e2e_tests/docker/indexer-filtered/e2e-read/Dockerfile
  e2e_tests/docker/indexer-filtered/e2e-write/Dockerfile
  e2e_tests/docker/indexer/Dockerfile
  e2e_tests/src/e2e_common/util.py
  e2e_tests/src/e2e_indexer/e2elive.py
  e2e_tests/src/e2e_indexer/validate_accounting.py
  go.mod
  go.sum
Labels: Enhancement

#1536 deps: Update go-algorand-sdk.
  go.mod
  go.sum
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_test.go
  protocol/config/config.go
  protocol/consensus.go
  util/test/account_testutil.go
  util/util.go
Labels: Enhancement

#1538 tests: Fix flaky test.
  idb/postgres/internal/writer/writer_test.go
Labels: Team Lamprey, Bug-Fix

#1530 encoding: Fix partupdrmv encoding.
  idb/postgres/internal/encoding/encoding.go
  idb/postgres/internal/encoding/encoding_test.go
  idb/postgres/internal/encoding/types.go
Labels: Bug-Fix
