Repository algorand/indexer, pull requests merged in 2023-02, with the labels that each got.

#1450 tests: Update e2e dockerfile
  .circleci/config.yml
  Makefile
  e2e_tests/docker/indexer/Dockerfile
Labels: Enhancement

#1458 e2e-tests: Add more log files on failure
  e2e_tests/src/e2e_indexer/e2elive.py
Labels: Enhancement

#1459 API: Add auth addr to transactions in responses.
  api/converter_utils.go
Labels: Bug-Fix

#1453 logging: Fix log-file configuration.
  cmd/conduit/main.go
  cmd/conduit/main_test.go
  loggers/loggers.go
  loggers/loggers_test.go
Labels: Bug-Fix

#1431 e2e-test: E2e sync mode test
  .circleci/config.yml
  Makefile
  e2e_tests/src/e2e_conduit/e2econduit.py
  e2e_tests/src/e2e_conduit/fixtures/exporters/postgresql.py
  e2e_tests/src/e2e_conduit/fixtures/importers/__init__.py
  e2e_tests/src/e2e_conduit/fixtures/importers/follower_algod.py
  e2e_tests/src/e2e_conduit/scenarios/follower_indexer_scenario.py
Labels: Enhancement

#1465 idb: update AddBlock method signature
  api/app_boxes_fixtures_test.go
  api/handlers_e2e_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  idb/dummy/dummy.go
  idb/idb.go
  idb/mocks/IndexerDb.go
  idb/postgres/postgres.go
  idb/postgres/postgres_boxes_test.go
  idb/postgres/postgres_integration_common_test.go
  idb/postgres/postgres_integration_test.go
  importer/importer.go
  types/types.go
  util/test/testutil.go
Labels: Enhancement, Team Lamprey

#1463 filter-processor: move reflection into generated code
  conduit/plugins/processors/filterprocessor/expression/expression.go
  conduit/plugins/processors/filterprocessor/fields/generated_signed_txn_map.go
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/fields/searcher_test.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
  conduit/plugins/processors/filterprocessor/gen/generate_test.go
  conduit/plugins/processors/filterprocessor/gen/internal/utils.go
Labels: Enhancement

#1452 algod importer: Combines algod and algod_follower
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/algod/algod_importer_config.go
  conduit/plugins/importers/algod/algod_importer_test.go
  conduit/plugins/importers/algod/sample.yaml
  conduit/plugins/importers/algodfollower/algodfollower_importer.go
  conduit/plugins/importers/algodfollower/algodfollower_importer_config.go
  conduit/plugins/importers/algodfollower/algodfollower_importer_test.go
  conduit/plugins/importers/algodfollower/metrics.go
  conduit/plugins/importers/algodfollower/sample.yaml
  conduit/plugins/importers/all/all.go
  e2e_tests/src/e2e_conduit/fixtures/importers/follower_algod.py
Labels: Enhancement

#1468 filter-processor: Remove reflection
  conduit/plugins/processors/filterprocessor/expression/expression.go
  conduit/plugins/processors/filterprocessor/expression/expression_test.go
  conduit/plugins/processors/filterprocessor/expression/numerical_expressions.go
  conduit/plugins/processors/filterprocessor/fields/generated_signed_txn_map.go
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/fields/searcher_test.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
  conduit/plugins/processors/filterprocessor/gen/generate_test.go
Labels: Enhancement

#1477 docs: Run conduit-docs directly.
  Makefile
  cmd/conduit-docs/README.md
  conduit/plugins/exporters/filewriter/file_exporter_config.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_config.go
  conduit/plugins/importers/algod/algod_importer_config.go
  conduit/plugins/importers/filereader/filereader_config.go
  conduit/plugins/processors/blockprocessor/config.go
  conduit/plugins/processors/filterprocessor/config.go
Labels: Enhancement

#1473 conduit: update plugin interface types
  conduit/init_provider.go
  conduit/pipeline/pipeline.go
  conduit/pipeline/pipeline_test.go
  conduit/plugins/exporters/filewriter/file_exporter_test.go
  conduit/plugins/exporters/noop/noop_exporter_test.go
  conduit/plugins/exporters/postgresql/postgresql_exporter.go
  conduit/plugins/exporters/postgresql/postgresql_exporter_test.go
  conduit/plugins/importers/algod/algod_importer.go
  conduit/plugins/importers/filereader/filereader_test.go
  conduit/plugins/processors/blockprocessor/block_processor.go
  conduit/plugins/processors/blockprocessor/config_test.go
  conduit/plugins/processors/filterprocessor/fields/filter.go
  conduit/plugins/processors/filterprocessor/fields/generated_signed_txn_map.go
  conduit/plugins/processors/filterprocessor/fields/searcher.go
  conduit/plugins/processors/filterprocessor/fields/searcher_test.go
  conduit/plugins/processors/filterprocessor/filter_processor.go
  conduit/plugins/processors/filterprocessor/filter_processor_bench_test.go
  conduit/plugins/processors/filterprocessor/filter_processor_test.go
  conduit/plugins/processors/filterprocessor/gen/generate.go
  data/block_export_data.go
  helpers/helpers.go
  util/test/testutil.go
Labels: Enhancement, Team Lamprey

#1478 algod: Importer Plugin Update
  conduit/plugins/importers/algod/algod_importer.go
  go.mod
  go.sum
  util/test/mock_algod.go
Labels: Enhancement

#1481 api: Remove go-algorand dep from api pkg
  api/app_boxes_fixtures_test.go
  api/converter_utils.go
  api/handlers.go
  api/handlers_e2e_test.go
  api/handlers_test.go
  api/pointer_utils.go
  util/test/account_testutil.go
Labels: Enhancement
